sudo: required

addons:
  apt:
    packages: haveged

services:
  - docker

language: ruby

rvm:
  - "2.1"
  - "2.3"

gemfile:
  - "gemfiles/rails_4.0.gemfile"
  - "gemfiles/rails_4.1.gemfile"
  - "gemfiles/rails_4.2.gemfile"
  - "gemfiles/rails_5.0.gemfile"

env:
  - CASSANDRA_VERSION: 2.1
  - CASSANDRA_VERSION: 2.2
  - CASSANDRA_VERSION: 3.0

script: script/ci-unit-test

bundler_args: '--without=debug'

matrix:
  exclude:
  - rvm: "2.1"
    gemfile: gemfiles/rails_5.0.gemfile
